import Head from 'next/head';
import { Card } from '@mui/joy';
import styles from '@/styles/Home.module.css';
import styled from '@emotion/styled';

const Initials = styled.div`
  position: absolute;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 60px;
  color: white;
  top: 35px;
  left: 35px;
  width: 150px;
  height: 150px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Card
          sx={{
            width: 628,
            height: 527,
            background: 'radial-gradient(300px circle at 110px 110px, transparent 25%, white 25%)',
          }}
        >
          <Initials>AD</Initials>
        </Card>
      </main>
    </>
  );
}
