import Head from 'next/head';

import ContactSection from '@/components/ContactSection';
import Footer from '@/components/Footer';
import ItemSection from '@/components/ItemSection';
import styles from '@/styles/Home.module.css';
import Layout from '@/components/Layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isHomePage>
        <div className={styles.sections}>
          <ContactSection />
          <ItemSection />
        </div>
        <Footer />
      </Layout>
    </>
  );
}
